## USB port
port: /dev/imu

##### Calibration ####
### accelerometer
accel_x_min: -251.59
accel_x_max: 264.89
accel_y_min: -250.98
accel_y_max: 259.16
accel_z_min: -249.51
accel_z_max: 265.75

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [80.7095, -374.308, -930.341]
magn_ellipsoid_transform: [[0.973846, 0.0103487, -0.00379147], [0.0103487, 0.979434, -0.00690649], [-0.00379147, -0.00690649, 0.995160]]


# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -0.02
gyro_average_offset_y: 0.02
gyro_average_offset_z: 0.01
