## USB port
port: /dev/imu

##### Calibration ####
### accelerometer
accel_x_min: -250.49
accel_x_max: 257.93
accel_y_min: -249.51
accel_y_max: 258.30
accel_z_min: -267.70
accel_z_max: 250.73

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [-11.5856, 204.024, 439.815]
magn_ellipsoid_transform: [[0.996995, 0.00534881, 0.0126958], [0.00534881, 0.978232, -0.0197772], [0.0126958, -0.0197772, 0.945709]]


# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 0.01
gyro_average_offset_y: -0.04
gyro_average_offset_z: 0.00
